export const SET_PROFILE = 'SET_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_SNACKBAR = 'SET_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES';
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const MARK_MESSAGE_READ = 'MARK_MESSAGE_READ';
export const CLEAR_CHAT_MESSAGES = 'CLEAR_CHAT_MESSAGES';
export const SET_NEW_MESSAGES = 'SET_NEW_MESSAGES';
export const SET_DININGMATES = 'SET_DININGMATES';
export const CLEAR_DININGMATES = 'CLEAR_DININGMATES';

export const SET_ROUTER_LOCATION = 'SET_ROUTER_LOCATION';
export const UNSET_ROUTER_LOCATION = 'UNSET_ROUTER_LOCATION';

export const SET_RESTAURANTPICKER = 'SET_RESTAURANTPICKER';
export const CLEAR_RESTAURANTPICKER = 'CLEAR_RESTAURANTPICKER';

export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
